class ContactsCallback:
    CONTACTS = 'contacts'
    ID = f'_id_{CONTACTS}'
    DELETE = f'delete_{CONTACTS}'
    DELETE_CONFIRM = f'confirm_del_{CONTACTS}'
    CANCEL = f'cancel_{CONTACTS}'
    ADD_CONTACT = f'add_{CONTACTS}'
    CHANGE_NAME = f'name_{CONTACTS}'
    CHANGE_CONTACT = f'phone_{CONTACTS}'
    BACK_TO_CONTACTS = f'back_to_contacts{CONTACTS}'
